### ISSUE TITLE
Average speed from front and rear right wheel

### ISSUE THREAD

**Issue by LatteG** [petrosdeb/Group-Stierna#2]
At the moment it just adds the value (speed or distance). This should probably be averaged instead.

https://github.com/petrosdeb/Group-Stierna/blob/1da7b3b873da2f346780cfbfcb2af3a3ddee5623/Code/src/Plugins/ConstantSpeed.java#L54

**Comment by petrosdeb** [comment]
Since this will only be used for comparison between the old and the new value, it should not make a difference it we average the two values or not.
